/*
Fleet Spec Sheet Generator — Illustrator (V1)

2-page print-friendly default:
- Page 1: Mockup (proof) + Install Sign-Off
- Page 2: Production section (Print Manifest)

Artboard rules:
- Proof artboard name contains: PROOF or MOCKUP (case-insensitive)
- Ignored artboards:
  - name contains 'unit' anywhere (case-insensitive)
  - OR name is pure digits (e.g. '4519')
  - OR is one of the spec-sheet artboards generated by this script
- Qty parsing: QTY2, QTY_2, QTY-2, QTY 2, x2, 2x

Scale rule:
- If artboard name contains @NN% (e.g. drum_logo_@50%), treat artwork as NN% scale.
- Reported WIDTH/HEIGHT are divided by scale (50% => 2x real size).
- SQ FT divided by scale^2.
- Prefix grouping ignores the @NN% token.

Notes:
- ExtendScript is ES3-ish: NO trailing commas.
- Re-run updates the existing pages (does not create duplicates).
*/

(function () {
  if (app.documents.length === 0) return;
  var doc = app.activeDocument;

  var IN = 72;
  var PAGE_W = 8.5 * IN;
  var PAGE_H_MIN = 11 * IN;

  var MARGIN = 0.25 * IN;
  var X0 = MARGIN;
  var CONTENT_W = PAGE_W - 2 * MARGIN;

  var HEADER_H = 0.45 * IN;
  var HEADER_TEXT = "BUFFALO GRAPHICS COMPANY";

  var DETAILS_H = 0.6 * IN;

  var PROOF_OUTER_W = CONTENT_W;
  var PROOF_INNER_W = CONTENT_W - 0.3 * IN;

  var MANIFEST_TITLE_H = 0.25 * IN;
  var MANIFEST_TITLE_GAP = 0.12 * IN;
  var MANIFEST_HDR_H = 0.32 * IN;
  var ROW_H = 0.85 * IN;

  var COL_W = {
    thumb: 1.4 * IN,
    name: 1.4 * IN,
    len: 1.3 * IN,
    wid: 1.3 * IN,
    sqft: 0.5 * IN,
    qty: 0.7 * IN,
    done: 0.9 * IN,
  };

  // Thumbnail fit box (inside the THUMBNAIL cell)
  var THUMB_PAD = 0.1 * IN;
  var THUMB_BOX_W = COL_W.thumb - 2 * THUMB_PAD;
  var THUMB_BOX_H = ROW_H - 2 * THUMB_PAD;

  var SIGN_TITLE_GAP = 0.2 * IN;
  var SIGN_TITLE_H = 0.25 * IN;
  var SIGN_TABLE_GAP = 0.28 * IN;

  function trim(s) {
    return String(s || "").replace(/^\s+|\s+$/g, "");
  }

  function tryFont(name) {
    try {
      return app.textFonts.getByName(name);
    } catch (e) {
      return null;
    }
  }

  function findFontContains(substr) {
    try {
      var needle = String(substr || "").toLowerCase();
      for (var i = 0; i < app.textFonts.length; i++) {
        var f = app.textFonts[i];
        var n = f && f.name ? String(f.name).toLowerCase() : "";
        var fam = f && f.family ? String(f.family).toLowerCase() : "";
        if (n.indexOf(needle) !== -1 || fam.indexOf(needle) !== -1) return f;
      }
    } catch (e) {}
    return null;
  }

  var HUDSON =
    tryFont("HudsonNY") ||
    tryFont("Hudson NY") ||
    tryFont("HudsonNY-Regular") ||
    findFontContains("hudson");

  function setText(tf, size, rgb, fontObj) {
    var tr = tf.textRange;
    tr.characterAttributes.size = size;
    if (fontObj) tr.characterAttributes.textFont = fontObj;
    else if (HUDSON) tr.characterAttributes.textFont = HUDSON;
    if (rgb) {
      var c = new RGBColor();
      c.red = rgb[0];
      c.green = rgb[1];
      c.blue = rgb[2];
      tr.characterAttributes.fillColor = c;
    }
  }

  function strokeBlack(item, w) {
    item.stroked = true;
    item.strokeWidth = w || 1;
    var c = new RGBColor();
    c.red = 0;
    c.green = 0;
    c.blue = 0;
    item.strokeColor = c;
    item.filled = false;
  }

  function fillBlack(item) {
    item.filled = true;
    var c = new RGBColor();
    c.red = 0;
    c.green = 0;
    c.blue = 0;
    item.fillColor = c;
    item.stroked = false;
  }

  function addRect(container, left, top, w, h, fill) {
    var r = container.pathItems.rectangle(top, left, w, h);
    if (fill) fillBlack(r);
    else strokeBlack(r, 1);
    return r;
  }

  function addLine(container, x1, y1, x2, y2) {
    var ln = container.pathItems.add();
    ln.setEntirePath([
      [x1, y1],
      [x2, y2],
    ]);
    strokeBlack(ln, 1);
    return ln;
  }

  function addAreaText(
    container,
    left,
    top,
    w,
    h,
    s,
    size,
    rgb,
    fontObj,
    justify,
  ) {
    var box = container.pathItems.rectangle(top, left, w, h);
    box.stroked = false;
    box.filled = false;
    var tf = container.textFrames.areaText(box);
    tf.contents = s;
    setText(tf, size, rgb, fontObj);
    if (justify) {
      try {
        tf.textRange.paragraphAttributes.justification = justify;
      } catch (e) {}
    }
    return tf;
  }

  function parseQty(name) {
    var n = String(name || "");
    var m;
    m = n.match(/(?:^|[_\-\s])qty(?:[_\-\s]*)(\d+)(?:[_\-\s\.]|$)/i);
    if (m) return parseInt(m[1], 10);
    m = n.match(/(?:^|[_\-\s])x(\d+)(?:[_\-\s\.]|$)/i);
    if (m) return parseInt(m[1], 10);
    m = n.match(/(?:^|[_\-\s])(\d+)x(?:[_\-\s\.]|$)/i);
    if (m) return parseInt(m[1], 10);
    return 1;
  }

  function parseScaleFromName(name) {
    var n = String(name || "");
    var m = n.match(/@(\d+(?:\.\d+)?)\s*%/i);
    if (!m) return 1;
    var p = parseFloat(m[1]);
    if (!isFinite(p) || p <= 0) return 1;
    return p / 100;
  }

  function stripScaleTag(name) {
    return String(name || "").replace(/@\d+(?:\.\d+)?\s*%/gi, "");
  }

  function formatInches(v) {
    var n = Math.round(v * 100) / 100;
    var s = String(n);
    if (s.indexOf(".") !== -1) s = s.replace(/0+$/, "").replace(/\.$/, "");
    return s;
  }

  function formatSqFt(v) {
    var n = Math.round(v * 100) / 100;
    var s = String(n);
    if (s.indexOf(".") !== -1) s = s.replace(/0+$/, "").replace(/\.$/, "");
    return s;
  }

  // Reported as WIDTH/HEIGHT (matches table labels)
  function artboardDimsWH(abIndex, scale) {
    try {
      var r = doc.artboards[abIndex].artboardRect;
      var wIn = (r[2] - r[0]) / IN;
      var hIn = (r[1] - r[3]) / IN;
      var s = scale && scale > 0 ? scale : 1;
      var mult = 1 / s;
      return {
        w: formatInches(wIn * mult) + '"',
        h: formatInches(hIn * mult) + '"',
      };
    } catch (e) {
      return { w: "", h: "" };
    }
  }

  function artboardSqFtText(abIndex, scale) {
    try {
      var r = doc.artboards[abIndex].artboardRect;
      var wIn = (r[2] - r[0]) / IN;
      var hIn = (r[1] - r[3]) / IN;
      var s = scale && scale > 0 ? scale : 1;
      var sqft = (wIn * hIn) / 144 / (s * s);
      return formatSqFt(sqft);
    } catch (e) {
      return "";
    }
  }

  function artboardSqFt(abIndex, scale) {
    try {
      var r = doc.artboards[abIndex].artboardRect;
      var wIn = (r[2] - r[0]) / IN;
      var hIn = (r[1] - r[3]) / IN;
      var s = scale && scale > 0 ? scale : 1;
      return (wIn * hIn) / 144 / (s * s);
    } catch (e) {
      return 0;
    }
  }

  function isProofArtboard(name) {
    var n = String(name || "");
    return /proof/i.test(n) || /mockup/i.test(n);
  }

  function isSpecArtboardName(name) {
    var n = String(name || "");
    return /^\s*spec\s+sheet\s*\(v1\)/i.test(n);
  }

  function isIgnoredArtboard(name) {
    if (!name) return false;
    var nRaw = trim(String(name));

    if (isSpecArtboardName(nRaw)) return true;

    var n = nRaw;
    n = n.replace(/^\s*\d+\s*([\-\._]|\u2013|\u2014)\s*/g, "");
    n = n.replace(/^\s*\d+\s+/, "");

    if (/unit/i.test(n)) return true;
    if (/^\d+$/.test(n)) return true;

    return false;
  }

  function normalizeForPrefix(name) {
    var n = trim(stripScaleTag(String(name || "")));
    n = n.replace(/^\s*\d+\s*([\-\._]|\u2013|\u2014)\s*/g, "");
    n = n.replace(/^\s*\d+\s+/, "");
    return trim(n);
  }

  function firstWordPrefix(name) {
    var n = normalizeForPrefix(name);
    if (!n) return "";
    var parts = n.split(/[\s_\-]+/);
    return parts && parts.length ? String(parts[0]) : "";
  }

  function getClientsSegmentsFromDocPath(docRef) {
    try {
      var f = null;
      try {
        f = docRef.fullName;
      } catch (e0) {
        f = null;
      }
      if (!f) return null;
      var norm = String(f.fsName || f.fullName || "").replace(/\\/g, "/");
      var parts = norm.split("/");
      var idx = -1;
      for (var i = 0; i < parts.length; i++) {
        if (String(parts[i]).toLowerCase() === "clients") {
          idx = i;
          break;
        }
      }
      if (idx === -1) return null;
      return {
        customer: trim(parts[idx + 1] || ""),
        job: trim(parts[idx + 2] || ""),
      };
    } catch (e) {
      return null;
    }
  }

  function inferCustomerFromDocPath(docRef) {
    var seg = getClientsSegmentsFromDocPath(docRef);
    return seg && seg.customer ? seg.customer : "";
  }

  function inferVehicleFromDocPath(docRef) {
    var seg = getClientsSegmentsFromDocPath(docRef);
    return seg && seg.job ? seg.job : "";
  }

  function makeDetailsDialog(defaultCustomer, defaultVehicle) {
    var w = new Window("dialog", "Spec Sheet Details");
    w.orientation = "column";
    w.alignChildren = ["fill", "top"];

    var g1 = w.add("group");
    g1.add("statictext", undefined, "Customer:");
    var customer = g1.add("edittext", undefined, defaultCustomer || "");
    customer.characters = 38;

    var g2 = w.add("group");
    g2.add("statictext", undefined, "Vehicle:");
    var vehicle = g2.add("edittext", undefined, defaultVehicle || "");
    vehicle.characters = 38;

    var btns = w.add("group");
    btns.alignment = "right";
    btns.add("button", undefined, "Cancel", { name: "cancel" });
    btns.add("button", undefined, "OK", { name: "ok" });

    customer.active = true;
    if (w.show() !== 1) return null;

    return { customer: trim(customer.text), vehicle: trim(vehicle.text) };
  }

  function duplicateArtboardArtworkToGroup(
    abIndex,
    targetGroup,
    excludeLayerName,
  ) {
    try {
      doc.selection = null;
    } catch (e0) {}
    try {
      doc.artboards.setActiveArtboardIndex(abIndex);
    } catch (e1) {}
    try {
      doc.selectObjectsOnActiveArtboard();
    } catch (e2) {}

    var sel = [];
    try {
      sel = doc.selection || [];
    } catch (e3) {
      sel = [];
    }

    for (var i = 0; i < sel.length; i++) {
      var it = sel[i];
      try {
        if (!it || it.locked || it.hidden) continue;
        if (excludeLayerName && it.layer && it.layer.name === excludeLayerName)
          continue;
        it.duplicate(targetGroup, ElementPlacement.PLACEATEND);
      } catch (e4) {}
    }

    try {
      doc.selection = null;
    } catch (e5) {}
  }

  function fitGroupToBox(group, boxW, boxH) {
    var vb = group.visibleBounds;
    var w = vb[2] - vb[0];
    var h = vb[1] - vb[3];
    if (w <= 0 || h <= 0) return;
    var s = Math.min(boxW / w, boxH / h) * 100;
    group.resize(s, s, true, true, true, true, s, Transformation.CENTER);
  }

  function autoOrientGroupToBox(group, boxW, boxH) {
    var vb = group.visibleBounds;
    var w = vb[2] - vb[0];
    var h = vb[1] - vb[3];
    if (w <= 0 || h <= 0) return;

    var s0 = Math.min(boxW / w, boxH / h);
    var s90 = Math.min(boxW / h, boxH / w);

    if (s90 > s0 * 1.05) {
      group.rotate(90, true, true, true, true, Transformation.CENTER);
    }
  }

  function centerGroupInBox(group, boxLeft, boxTop, boxW, boxH) {
    var vb = group.visibleBounds;
    var w = vb[2] - vb[0];
    var h = vb[1] - vb[3];

    var cx = boxLeft + boxW / 2;
    var cy = boxTop - boxH / 2;

    var curL = vb[0];
    var curT = vb[1];

    var targetL = cx - w / 2;
    var targetT = cy + h / 2;

    group.translate(targetL - curL, targetT - curT);
  }

  function rasterizeItem(item) {
    try {
      if (!item) return null;
      var vb = item.visibleBounds;
      if (!vb || vb.length !== 4) return null;

      var ro = new RasterizeOptions();
      ro.resolution = 300;
      ro.antiAliasingMethod = AntiAliasingMethod.ARTOPTIMIZED;
      ro.transparency = true;
      ro.backgroundBlack = false;
      try {
        ro.convertSpotColors = false;
      } catch (e0) {}

      var r = doc.rasterize(item, vb, ro);
      try {
        item.remove();
      } catch (e1) {}
      return r;
    } catch (e) {
      return null;
    }
  }

  function getOrCreateSpecLayer() {
    for (var i = 0; i < doc.layers.length; i++) {
      if (doc.layers[i].name === "SPEC SHEET (V1)") return doc.layers[i];
    }
    var lyr = doc.layers.add();
    lyr.name = "SPEC SHEET (V1)";
    return lyr;
  }

  function clearLayer(layer) {
    try {
      for (var i = layer.pageItems.length - 1; i >= 0; i--) {
        try {
          layer.pageItems[i].remove();
        } catch (e1) {}
      }
      for (var j = layer.layers.length - 1; j >= 0; j--) {
        try {
          layer.layers[j].remove();
        } catch (e2) {}
      }
    } catch (e) {}
  }

  function ensureMinPageHeight(top, bottom) {
    var minBottom = top - PAGE_H_MIN;
    return Math.min(bottom, minBottom);
  }

  function setArtboardRect(abIdx, left, top, width, bottom) {
    try {
      var ab = doc.artboards[abIdx];
      if (!ab) return;
      var btm = ensureMinPageHeight(top, bottom);
      ab.artboardRect = [left, top, left + width, btm];
    } catch (e) {}
  }

  function findArtboardByNameExact(name) {
    for (var i = 0; i < doc.artboards.length; i++) {
      if (String(doc.artboards[i].name || "") === name) return i;
    }
    return -1;
  }

  function findLegacySingleSpecArtboard() {
    for (var i = 0; i < doc.artboards.length; i++) {
      if (String(doc.artboards[i].name || "").indexOf("SPEC SHEET (V1)") === 0)
        return i;
    }
    return -1;
  }

  function getOrCreateTwoSpecArtboards() {
    var nameInstall = "SPEC SHEET (V1) - INSTALL";
    var nameProd = "SPEC SHEET (V1) - PRODUCTION";

    var idxInstall = findArtboardByNameExact(nameInstall);
    var idxProd = findArtboardByNameExact(nameProd);

    // legacy single artboard -> becomes INSTALL
    if (idxInstall === -1 && idxProd === -1) {
      var legacy = findLegacySingleSpecArtboard();
      if (legacy !== -1) {
        try {
          doc.artboards[legacy].name = nameInstall;
        } catch (e0) {}
        idxInstall = legacy;
      }
    }

    var gap = 0.5 * IN;

    if (idxInstall === -1) {
      var maxRight = -1e12;
      var topAlign = doc.artboards[0].artboardRect[1];
      for (var i = 0; i < doc.artboards.length; i++) {
        var rr = doc.artboards[i].artboardRect;
        if (rr[2] > maxRight) maxRight = rr[2];
      }
      var left = maxRight + gap;
      var top = topAlign;
      doc.artboards.add([left, top, left + PAGE_W, top - PAGE_H_MIN]);
      idxInstall = doc.artboards.length - 1;
      try {
        doc.artboards[idxInstall].name = nameInstall;
      } catch (e1) {}
    }

    if (idxProd === -1) {
      var rInst = doc.artboards[idxInstall].artboardRect;
      var left2 = rInst[2] + gap;
      var top2 = rInst[1];
      doc.artboards.add([left2, top2, left2 + PAGE_W, top2 - PAGE_H_MIN]);
      idxProd = doc.artboards.length - 1;
      try {
        doc.artboards[idxProd].name = nameProd;
      } catch (e2) {}
    }

    return { install: idxInstall, production: idxProd };
  }

  function drawHeaderOnly(root, pageLeft, pageTop) {
    // Header bar only (no customer/vehicle table)
    addRect(root, pageLeft, pageTop, PAGE_W, HEADER_H, true);
    addAreaText(
      root,
      pageLeft + 0.18 * IN,
      pageTop - 0.12 * IN,
      PAGE_W - 0.36 * IN,
      HEADER_H,
      HEADER_TEXT,
      14,
      [255, 255, 255],
      HUDSON,
    );

    // Return next Y position below the header
    return pageTop - HEADER_H - 0.12 * IN;
  }

  function drawHeaderAndDetails(root, pageLeft, pageTop, details) {
    var y = pageTop;

    addRect(root, pageLeft, pageTop, PAGE_W, HEADER_H, true);
    addAreaText(
      root,
      pageLeft + 0.18 * IN,
      pageTop - 0.12 * IN,
      PAGE_W - 0.36 * IN,
      HEADER_H,
      HEADER_TEXT,
      14,
      [255, 255, 255],
      HUDSON,
    );

    y = pageTop - HEADER_H - 0.12 * IN;

    var tableLeft = pageLeft + X0;
    var tableTop = y;
    var tableW = CONTENT_W;
    var rowH = DETAILS_H / 2;

    addRect(root, tableLeft, tableTop, tableW, DETAILS_H, false);
    addLine(
      root,
      tableLeft,
      tableTop - rowH,
      tableLeft + tableW,
      tableTop - rowH,
    );

    var c1 = 1.2 * IN;
    var c2 = 4.4 * IN;
    var c5 = 1.3 * IN;
    var c6 = 0.6 * IN;

    addLine(
      root,
      tableLeft + c1,
      tableTop,
      tableLeft + c1,
      tableTop - DETAILS_H,
    );
    addLine(
      root,
      tableLeft + c1 + c2,
      tableTop - rowH,
      tableLeft + c1 + c2,
      tableTop - DETAILS_H,
    );
    addLine(
      root,
      tableLeft + tableW - (c5 + c6),
      tableTop - rowH,
      tableLeft + tableW - (c5 + c6),
      tableTop - DETAILS_H,
    );
    addLine(
      root,
      tableLeft + tableW - c6,
      tableTop - rowH,
      tableLeft + tableW - c6,
      tableTop - DETAILS_H,
    );

    addAreaText(
      root,
      tableLeft + 0.08 * IN,
      tableTop - 0.14 * IN,
      c1 - 0.16 * IN,
      rowH,
      "CUSTOMER:",
      9,
      [0, 0, 0],
      HUDSON,
    );
    addAreaText(
      root,
      tableLeft + c1 + 0.08 * IN,
      tableTop - 0.14 * IN,
      tableW - c1 - 0.16 * IN,
      rowH,
      details.customer,
      9,
      [0, 0, 0],
      HUDSON,
    );

    var row2Top = tableTop - rowH;
    addAreaText(
      root,
      tableLeft + 0.08 * IN,
      row2Top - 0.14 * IN,
      c1 - 0.16 * IN,
      rowH,
      "VEHICLE:",
      9,
      [0, 0, 0],
      HUDSON,
    );
    addAreaText(
      root,
      tableLeft + c1 + 0.08 * IN,
      row2Top - 0.14 * IN,
      c2 - 0.16 * IN,
      rowH,
      details.vehicle,
      9,
      [0, 0, 0],
      HUDSON,
    );
    addAreaText(
      root,
      tableLeft + tableW - (c5 + c6) + 0.08 * IN,
      row2Top - 0.14 * IN,
      c5 - 0.16 * IN,
      rowH,
      "VEHICLE UNIT #:",
      9,
      [0, 0, 0],
      HUDSON,
    );

    y = tableTop - DETAILS_H - 0.18 * IN;
    return y;
  }

  function drawInstallSignOff(root, pageLeft, yStart) {
    var y = yStart;

    y -= SIGN_TITLE_GAP;
    addAreaText(
      root,
      pageLeft + X0,
      y,
      CONTENT_W,
      SIGN_TITLE_H,
      "INSTALL SIGN-OFF",
      11,
      [0, 0, 0],
      HUDSON,
    );
    addLine(
      root,
      pageLeft + X0,
      y - 0.2 * IN,
      pageLeft + X0 + 1.75 * IN,
      y - 0.2 * IN,
    );
    y -= SIGN_TITLE_H;
    y -= SIGN_TABLE_GAP;

    var signX = pageLeft + X0;
    var signTop = y;
    var signW = CONTENT_W;

    var widths = [1.3 * IN, 2.2 * IN, 1.1 * IN, 0.9 * IN, 0.7 * IN, 1.3 * IN];
    var signRow1 = 0.35 * IN;
    var signRow2 = 1.2 * IN;
    var signH = signRow1 + signRow2;

    addRect(root, signX, signTop, signW, signH, false);
    addLine(root, signX, signTop - signRow1, signX + signW, signTop - signRow1);

    var cx = signX;
    for (var c = 0; c < widths.length - 1; c++) {
      cx += widths[c];
      addLine(root, cx, signTop, cx, signTop - signRow1);
    }
    addLine(
      root,
      signX + widths[0],
      signTop - signRow1,
      signX + widths[0],
      signTop - signH,
    );

    var sx = signX;
    addAreaText(
      root,
      sx + 0.08 * IN,
      signTop - 0.11 * IN,
      widths[0] - 0.16 * IN,
      signRow1,
      "INSTALLED BY:",
      9,
      [0, 0, 0],
      HUDSON,
    );
    sx += widths[0] + widths[1];
    addAreaText(
      root,
      sx + 0.08 * IN,
      signTop - 0.11 * IN,
      widths[2] - 0.16 * IN,
      signRow1,
      "PHOTOS TAKEN:",
      9,
      [0, 0, 0],
      HUDSON,
    );
    sx += widths[2];
    addAreaText(
      root,
      sx + 0.1 * IN,
      signTop - 0.11 * IN,
      widths[3] - 0.2 * IN,
      signRow1,
      "YES   NO",
      9,
      [0, 0, 0],
      HUDSON,
    );
    sx += widths[3];
    addAreaText(
      root,
      sx + 0.08 * IN,
      signTop - 0.11 * IN,
      widths[4] - 0.16 * IN,
      signRow1,
      "DATE:",
      9,
      [0, 0, 0],
      HUDSON,
    );

    addAreaText(
      root,
      signX + 0.08 * IN,
      signTop - signRow1 - 0.14 * IN,
      widths[0] - 0.16 * IN,
      signRow2,
      "ISSUES / DAMAGE NOTES:",
      9,
      [0, 0, 0],
      HUDSON,
    );

    return { yEnd: signTop - signH, signTop: signTop, signH: signH };
  }

  // -------------------- Gather artboards --------------------
  var proofIdx = -1;
  var items = [];

  for (var ai = 0; ai < doc.artboards.length; ai++) {
    var abName = doc.artboards[ai].name || "Artboard " + (ai + 1);
    if (isIgnoredArtboard(abName)) continue;

    if (proofIdx === -1 && isProofArtboard(abName)) {
      proofIdx = ai;
      continue;
    }

    items.push({
      abIndex: ai,
      name: abName,
      qty: parseQty(abName),
      scale: parseScaleFromName(abName),
      prefix: firstWordPrefix(abName),
      _orig: items.length,
    });
  }

  if (proofIdx === -1) return;
  if (items.length === 0) return;

  // Sort: example first, then repeated prefixes, then uniques
  for (var i_sort = 0; i_sort < items.length; i_sort++) {
    var nm = stripScaleTag(String(items[i_sort].name || ""));
    var m = nm.match(/^([a-z0-9]+)/i);
    items[i_sort].prefix = m ? m[1] : "";
    items[i_sort]._orig = i_sort;
  }

  var prefixCount = {};
  for (var pc = 0; pc < items.length; pc++) {
    var p = String(items[pc].prefix || "").toLowerCase();
    prefixCount[p] = (prefixCount[p] || 0) + 1;
  }

  function bucketRank(it) {
    var p = String(it.prefix || "").toLowerCase();
    if (p === "example") return 0;
    if ((prefixCount[p] || 0) > 1) return 1;
    return 2;
  }

  items.sort(function (a, b) {
    var ra = bucketRank(a);
    var rb = bucketRank(b);
    if (ra !== rb) return ra - rb;

    var ap = String(a.prefix || "").toLowerCase();
    var bp = String(b.prefix || "").toLowerCase();
    if (ap < bp) return -1;
    if (ap > bp) return 1;

    return (a._orig || 0) - (b._orig || 0);
  });

  // Details prompt
  var inferredCustomer = inferCustomerFromDocPath(doc);
  var inferredVehicle = inferVehicleFromDocPath(doc);
  var details = makeDetailsDialog(inferredCustomer, inferredVehicle);
  if (!details) return;

  // Layer + pages
  var specLayer = getOrCreateSpecLayer();
  clearLayer(specLayer);

  var pages = getOrCreateTwoSpecArtboards();
  var installIdx = pages.install;
  var prodIdx = pages.production;

  var rootInstall = specLayer.groupItems.add();
  rootInstall.name = "__spec_install__";
  var rootProd = specLayer.groupItems.add();
  rootProd.name = "__spec_production__";

  // -------------------- PAGE 1 (INSTALL) --------------------
  doc.artboards.setActiveArtboardIndex(installIdx);
  var rInstall = doc.artboards[installIdx].artboardRect;
  var I_L = rInstall[0];
  var I_T = rInstall[1];

  var yI = drawHeaderAndDetails(rootInstall, I_L, I_T, details);

  // Proof
  var proofTop = yI;
  var proofGroup = rootInstall.groupItems.add();
  proofGroup.name = "__proof_group__";
  duplicateArtboardArtworkToGroup(proofIdx, proofGroup, "SPEC SHEET (V1)");
  fitGroupToBox(proofGroup, PROOF_INNER_W, 1000 * IN);

  var pvb = proofGroup.visibleBounds;
  var pW = pvb[2] - pvb[0];
  var pH = pvb[1] - pvb[3];

  var proofBoxLeft = I_L + X0;
  var proofInnerLeft = proofBoxLeft + (PROOF_OUTER_W - pW) / 2;
  proofGroup.translate(proofInnerLeft - pvb[0], proofTop - pvb[1]);
  rasterizeItem(proofGroup);

  yI = proofTop - pH - 0.18 * IN;

  var signInfo = drawInstallSignOff(rootInstall, I_L, yI);
  var installBottom = signInfo.yEnd - 0.25 * IN;
  setArtboardRect(installIdx, I_L, I_T, PAGE_W, installBottom);

  // -------------------- PAGE 2 (PRODUCTION) --------------------
  doc.artboards.setActiveArtboardIndex(prodIdx);
  var rProd = doc.artboards[prodIdx].artboardRect;
  var P_L = rProd[0];
  var P_T = rProd[1];

  var yP = drawHeaderOnly(rootProd, P_L, P_T);

  addAreaText(
    rootProd,
    P_L + X0,
    yP,
    CONTENT_W,
    MANIFEST_TITLE_H,
    "PRINT MANIFEST",
    11,
    [0, 0, 0],
    HUDSON,
  );

  var totalSqFt = 0;
  for (var tsi = 0; tsi < items.length; tsi++) {
    var it2 = items[tsi];
    var q = it2 && it2.qty ? Number(it2.qty) : 1;
    if (!q || q < 1) q = 1;
    totalSqFt += artboardSqFt(it2.abIndex, it2.scale) * q;
  }
  var totalSqText = "TOTAL SQ FT: " + formatSqFt(totalSqFt);
  addAreaText(
    rootProd,
    P_L + X0,
    yP,
    CONTENT_W,
    MANIFEST_TITLE_H,
    totalSqText,
    10,
    [0, 0, 0],
    HUDSON,
    Justification.RIGHT,
  );

  addLine(
    rootProd,
    P_L + X0,
    yP - 0.2 * IN,
    P_L + X0 + 1.7 * IN,
    yP - 0.2 * IN,
  );

  yP -= MANIFEST_TITLE_H;
  yP -= MANIFEST_TITLE_GAP;

  var tX = P_L + X0;
  var tY = yP;
  var tW = CONTENT_W;

  addRect(rootProd, tX, tY, tW, MANIFEST_HDR_H, false);

  var cols = [
    COL_W.thumb,
    COL_W.name,
    COL_W.len,
    COL_W.wid,
    COL_W.sqft,
    COL_W.qty,
    COL_W.done,
  ];
  var cx = tX;
  for (var ccol = 0; ccol < cols.length - 1; ccol++) {
    cx += cols[ccol];
    addLine(rootProd, cx, tY, cx, tY - MANIFEST_HDR_H);
  }

  var hx = tX;
  addAreaText(
    rootProd,
    hx + 0.08 * IN,
    tY - 0.12 * IN,
    cols[0] - 0.16 * IN,
    MANIFEST_HDR_H,
    "THUMBNAIL",
    9,
    [0, 0, 0],
    HUDSON,
  );
  hx += cols[0];
  addAreaText(
    rootProd,
    hx + 0.08 * IN,
    tY - 0.12 * IN,
    cols[1] - 0.16 * IN,
    MANIFEST_HDR_H,
    "NAME",
    9,
    [0, 0, 0],
    HUDSON,
  );
  hx += cols[1];
  addAreaText(
    rootProd,
    hx + 0.08 * IN,
    tY - 0.12 * IN,
    cols[2] - 0.16 * IN,
    MANIFEST_HDR_H,
    "WIDTH",
    9,
    [0, 0, 0],
    HUDSON,
  );
  hx += cols[2];
  addAreaText(
    rootProd,
    hx + 0.08 * IN,
    tY - 0.12 * IN,
    cols[3] - 0.16 * IN,
    MANIFEST_HDR_H,
    "HEIGHT",
    9,
    [0, 0, 0],
    HUDSON,
  );
  hx += cols[3];
  addAreaText(
    rootProd,
    hx + 0.06 * IN,
    tY - 0.12 * IN,
    cols[4] - 0.12 * IN,
    MANIFEST_HDR_H,
    "SQ FT",
    9,
    [0, 0, 0],
    HUDSON,
  );
  hx += cols[4];
  addAreaText(
    rootProd,
    hx + 0.1 * IN,
    tY - 0.12 * IN,
    cols[5] - 0.2 * IN,
    MANIFEST_HDR_H,
    "QTY",
    9,
    [0, 0, 0],
    HUDSON,
  );
  hx += cols[5];
  addAreaText(
    rootProd,
    hx + 0.08 * IN,
    tY - 0.12 * IN,
    cols[6] - 0.16 * IN,
    MANIFEST_HDR_H,
    "DONE",
    9,
    [0, 0, 0],
    HUDSON,
  );

  yP = tY - MANIFEST_HDR_H;

  for (var r = 0; r < items.length; r++) {
    var it = items[r];
    var rowTop = yP;

    addRect(rootProd, tX, rowTop, tW, ROW_H, false);

    cx = tX;
    for (var cc = 0; cc < cols.length - 1; cc++) {
      cx += cols[cc];
      addLine(rootProd, cx, rowTop, cx, rowTop - ROW_H);
    }

    var thumbGroup = rootProd.groupItems.add();
    thumbGroup.name = "__thumb_" + (r + 1) + "__";
    duplicateArtboardArtworkToGroup(it.abIndex, thumbGroup, "SPEC SHEET (V1)");
    autoOrientGroupToBox(thumbGroup, THUMB_BOX_W, THUMB_BOX_H);
    fitGroupToBox(thumbGroup, THUMB_BOX_W, THUMB_BOX_H);
    centerGroupInBox(thumbGroup, tX, rowTop, cols[0], ROW_H);
    rasterizeItem(thumbGroup);

    var textTop = rowTop - 0.14 * IN;
    var nameText = String(it.name || "").toUpperCase();
    var dims = artboardDimsWH(it.abIndex, it.scale);
    var sqftText = artboardSqFtText(it.abIndex, it.scale);
    var qtyText = String(it.qty);

    var tx = tX + cols[0];
    addAreaText(
      rootProd,
      tx + 0.08 * IN,
      textTop,
      cols[1] - 0.16 * IN,
      ROW_H,
      nameText,
      9,
      [0, 0, 0],
      HUDSON,
    );
    tx += cols[1];
    addAreaText(
      rootProd,
      tx + 0.08 * IN,
      textTop,
      cols[2] - 0.16 * IN,
      ROW_H,
      dims.w,
      9,
      [0, 0, 0],
      HUDSON,
    );
    tx += cols[2];
    addAreaText(
      rootProd,
      tx + 0.08 * IN,
      textTop,
      cols[3] - 0.16 * IN,
      ROW_H,
      dims.h,
      9,
      [0, 0, 0],
      HUDSON,
    );
    tx += cols[3];
    addAreaText(
      rootProd,
      tx + 0.06 * IN,
      textTop,
      cols[4] - 0.12 * IN,
      ROW_H,
      sqftText,
      9,
      [0, 0, 0],
      HUDSON,
    );
    tx += cols[4];
    addAreaText(
      rootProd,
      tx + 0.1 * IN,
      textTop,
      cols[5] - 0.2 * IN,
      ROW_H,
      qtyText,
      9,
      [0, 0, 0],
      HUDSON,
    );

    yP -= ROW_H;
  }

  var prodBottom = yP - 0.25 * IN;
  setArtboardRect(prodIdx, P_L, P_T, PAGE_W, prodBottom);

  try {
    specLayer.zOrder(ZOrderMethod.BRINGTOFRONT);
  } catch (eZ) {}
})();
